#
# GNU makefile
#
all: clean
	./test_unit.sh
	./test_streams.sh
	./test_bins.sh

debug: all

release: all

clean:
	rm -f *.raw *.flac *.cmp ../../test_files/*.raw *../../test_files/.flac *../../test_files/.cmp *.log core
