#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libgrabbag
INCLUDES = -I$(topdir)/include

OBJS = \
	file.o \
	replaygain.o \
	seektable.o

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
