!include <win32.mak>

# It's less hassle to spell it all out that to figure out how to do it right with nmake:

all:
	cd cuesheet
	nmake /f Makefile.vc
	cd ..

clean:
	cd cuesheet
	nmake /f Makefile.vc clean
	cd ..
