!include <win32.mak>

.c.obj:
	$(cc) $(cdebug) $(cflags) -DSTRICT -YX /O2 -DNODEBUG $<

C_FILES= \
	main.c

OBJS= $(C_FILES:.c=.obj)

all: flac_mac.exe

flac_mac.exe: $(OBJS)
	link.exe $(OBJS) -out:$*.exe

clean:
	-del *.obj *.pch
	-del flac_mac.exe
