#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libgain_analysis
INCLUDES = -I$(topdir)/include/share

OBJS = \
	gain_analysis.o

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
