#  test_libOggFLAC++ - Unit tester for libOggFLAC++
#  Copyright (C) 2002,2003  Josh Coalson
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

#
# GNU makefile
#

topdir = ../..

PROGRAM_NAME = test_libOggFLAC++
#@@@ TODO: conditionalize ogg lib path and -logg
INCLUDES     = -I$(topdir)/include
LIBS         = -lgrabbag -lreplaygain_analysis -lOggFLAC++ -lOggFLAC -lFLAC -L$(HOME)/local/lib -logg -lm
SRCS_C = \
	file_utils.c \
	metadata_utils.c
SRCS_CPP = \
	decoders.cpp \
	encoders.cpp \
	main.cpp

include $(topdir)/build/exe.mk

LINK = $(CCC) $(LINKAGE)

# DO NOT DELETE THIS LINE -- make depend depends on it.
