!include <win32.mak>

!IFDEF DEBUG
.c.obj:
	$(cc) $(cdebug) $(cflags) /I "..\..\include" /I ".\include" -DSTRICT -YX /Od /D "_DEBUG" $<
!else
.c.obj:
	$(cc) $(cdebug) $(cflags) /I "..\..\include" /I ".\include" -DSTRICT -YX /O2 -DNODEBUG $<
!endif

C_FILES= \
	decode.c \
	encode.c \
	main.c

OBJS= $(C_FILES:.c=.obj)

all: flac.exe

flac.exe: $(OBJS)
	link.exe /libpath:"..\..\obj\lib" -out:../../obj/bin/$*.exe $(OBJS) libFLAC.lib

clean:
	-del *.obj *.pch
	-del ..\..\obj\bin\flac.exe
