#
# GNU makefile
#

LIB_NAME  = libxmms-flac
INCLUDES  = $(shell xmms-config --cflags) -I./include -I../../include
LIBS = ../../obj/lib/libFLAC.a

OBJS = \
	plugin.o

include ../../build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
