#
# GNU makefile
#

LIB_NAME = libplugin-common
INCLUDES = -I../../include

OBJS = \
	canonical_tag.o \
	charset.o \
	dither.o \
	id3v1.o

include ../../build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
