#
# GNU makefile
#

topdir = ../..

LIB_NAME = libplugin_common
INCLUDES = -I$(topdir)/include -I$(HOME)/local/include
DEFINES  = -DFLAC__HAS_ID3LIB -DID3LIB_MAJOR=3 -DID3LIB_MINOR=8 -DID3LIB_PATCH=0

SRCS_C = \
	canonical_tag.c \
	charset.c \
	dither.c \
	id3v1.c \
	id3v2.c \
	vorbiscomment.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
