#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libutf8
INCLUDES = -I$(topdir)/include -I$(topdir)/include/share

OBJS = \
	charset.o \
	iconvert.o \
	utf8.o

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
