#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libutf8
INCLUDES = -I$(topdir)/include -I$(topdir)/include/share -I$(ICONV_INCLUDE_DIR)

SRCS_C = \
	charset.c \
	iconvert.c \
	utf8.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
