#
# GNU makefile
#

PROGRAM_NAME = metaflac
INCLUDES     = -I./include -I../../include
LIBS         = 

OBJS = \
	main.o

include ../../build/exe.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
