#
# GNU makefile
#

PROGRAM_NAME = test_unit
INCLUDES     = -I../libFLAC/include -I../../include
LIBS         = -lFLAC -lm
OBJS = \
	bitbuffer.o \
	main.o

include ../../build/exe.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
