#
# GNU makefile
#

PROGRAM_NAME = test_streams
INCLUDES     = -I./include -I../../include
LIBS         = -lm
OBJS = \
	main.o

include ../../build/exe.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
