#
# GNU makefile
#

LIB_NAME  = libFLAC
DEFINES = -DFLAC__PRECOMPUTE_PARTITION_SUMS -DFLAC__ALIGN_MALLOC_DATA
INCLUDES  = -I./include -I../../include
DEBUG_CFLAGS = -DFLAC__OVERFLOW_DETECT

OBJS = \
	bitbuffer.o \
	bitmath.o \
	crc.o \
	encoder.o \
	encoder_framing.o \
	file_decoder.o \
	fixed.o \
	format.o \
	lpc.o \
	md5.o \
	memory.o \
	seek_table.o \
	stream_decoder.o

include ../../build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
