#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libreplaygain
INCLUDES = -I$(topdir)/include

OBJS = \
	replaygain.o

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
