#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libfile_utils
INCLUDES = -I$(topdir)/include

OBJS = \
	file_utils.o

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
