#  test_libFLAC++ - Unit tester for libFLAC++
#  Copyright (C) 2002  Josh Coalson
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

#
# GNU makefile
#

topdir = ../..

PROGRAM_NAME = test_libFLAC++
INCLUDES     = -I$(topdir)/include
LIBS         = -lFLAC++ -lFLAC -lfile_utils -lm
OBJS = \
	decoders.o \
	encoders.o \
	file_utils.o \
	main.o \
	metadata.o \
	metadata_manip.o \
	metadata_object.o

include $(topdir)/build/exe.mk

LINK = $(CCC) $(LINKAGE)

# DO NOT DELETE THIS LINE -- make depend depends on it.
