#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libwin_utf8_io
INCLUDES = -I$(topdir)/include

SRCS_C = \
	win_utf8_io.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
