#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libgetopt
INCLUDES = -I$(topdir)/include -I$(topdir)/include/share

OBJS = \
	getopt.o \
	getopt1.o

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
